version: "3"

services:
    nominatim:
        container_name: nominatim
        # image: mediagis/nominatim:4.4
        build: nominatim-backend/
        ports:
            - "8080:8080"
        environment:
            # - ./.env
            # # see https://github.com/mediagis/nominatim-docker/tree/master/4.3#configuration for more options
            # PBF_URL: https://download.geofabrik.de/europe/monaco-latest.osm.pbf
            # PBF_URL: https://drive.usercontent.google.com/u/0/uc?id=1WpYAUkU5rYRtcEynv9w3COWsLLwpYa8m&export=download
            PBF_PATH: ../data/data.osm.pbf
            # # REPLICATION_URL: https://download.geofabrik.de/europe/monaco-updates/
            # NOMINATIM_PASSWORD: very_secure_password
        volumes:
            - ./data:/data
            # - nominatim-data:/var/lib/postgresql/14/main
        shm_size: 1gb

    nginx:
        restart: always
        container_name: app-nginx
        image: nginx
        ports:
            - 8090:80
        depends_on:
            - nominatim
        volumes:
            - ./nominatim-ui:/usr/share/nginx/html

# volumes:
#     nominatim-data:

# volumes:
#     data:
